### ISSUE TITLE
Is there a way to decrease the amount of memory needed?

### ISSUE THREAD

**Issue by Fustigate8933** [tshatrov/ichiran#66]
I am trying to hose Ichiran using docker on a free azure vm instance. However, I keep getting an error on the last step in docker compose build. On a machine with more memory, however, it works. So is there a way to decrease memory needed? Like a smaller dictionary or something?

**Comment by davidrideout** [comment]
If the build memory consumption is what's breaking it, you could build it on a higher specced machine and run it on the lower-specced azure instance. When I feed short sentences to `ichiran-cli` in a container, memory consumption spikes to under 250MB -- fairly low mem usage.

**Comment by davidrideout** [comment]
I just built the containers locally and pushed them to dockerhub. Then a slightly modified compose file:

`docker-compose.yml`:
```
services:
  pg:
    image: "therideout/ichi-db:latest"
    build:
      dockerfile: ./docker/postgres-dockerfile
      context: .
      args:
        ICHIRAN_DB_URL: "https://github.com/tshatrov/ichiran/releases/download/ichiran-240107/jmdict-070124.pgdump"
    shm_size: "1gb"
    environment:
      POSTGRES_PASSWORD: "password"
      PGDATA: "/var/lib/postgresql/data/pgdata"

  main:
    image: "therideout/ichi:latest"
    build:
      dockerfile: ./docker/sbcl-dockerfile
      context: .
```

Then
```
docker compose pull
docker compose up --no-build 
```

Worked for me, but ymmv.
